file : ~/.bashrc

http_proxy="http://127.0.0.1:12333"
export http_proxy
https_proxy="http://127.0.0.1:12333"
export https_proxy
ALL_PROXY="http://127.0.0.1:12333"
export ALL_PROXY

eval $(opam config env)

